### ISSUE TITLE
Investigate json-schema-ref-parser

### ISSUE THREAD

**Issue by mcollina** [fastify/fast-json-stringify#165]
https://www.npmjs.com/package/json-schema-ref-parser might avoid us to have some custom logic / avoid bugs when dealing with refs here. What do you think?

**Comment by Eomm** [comment]
This could be a good starting point since, now, there are some cases not covered (like urn).

I'm not sure about the bugs opened in that module, there are a some that seem really high-priority but still open.
I checked AJV, and they use an internal function to resolve $refs.

I'm more inclined to write a more complete function, so we can still be proponents of our destiny.

**Comment by mcollina** [comment]
+1!
