### ISSUE TITLE
Support for long integers

### ISSUE THREAD

**Issue by rochdev** [fastify/fast-json-stringify#28]
Support for 64bit integers as numbers instead of strings would be very useful. The use case being 3rd-party APIs that enforce it.

From my understanding, the `$asNumber` function could simply not convert the input to a `Number` and it would pretty much work as it (since the source long would be a string anyway). However, I don't know if that would introduce a backward compatibility issue.

Alternatively, the string could be validated with regex, but that might be too slow.

I thought about adding a `long` type but that doesn't exist in the JSON Schema specification.

What do you think?

**Comment by delvedor** [comment]
As far as I know 64 bit integers are a kind of PITA in javascript, since js uses the [IEEE-754](https://en.wikipedia.org/wiki/IEEE_floating_point#IEEE_754-2008) specification and does not have enough  digits to represent a 64 bit integer.
I think we must discuss about this and figure out if we can (and how) solve this issue.

Refs:
http://json-schema.org/latest/json-schema-core.html#rfc.section.5.3
https://tools.ietf.org/html/rfc7159#section-6

cc @mcollina

**Comment by rochdev** [comment]
After thinking on this a bit more, I think supporting the `Long` type from [long.js](https://github.com/dcodeIO/long.js) would be the way to go.

It would be the easiest way to implement longs, and very fast too since `Long.isLong()` only does an equality check. It is also what [protobuf.js](https://github.com/dcodeIO/protobuf.js) is using, so it would be great for interoperability.

I'll send a PR tonight.
